### PR TITLE
Use namespaced TestCase

### PR DESCRIPTION
**Pull request by ZeljkaBlazek**
This PR resolves:
* tests now extend from namespaced TestCase

### CODE REVIEW

**Comment by rosstuck** [comment]
Hi @ZeljkaBlazek, thanks for the PR, it looks good! Just curious, have you automated these upgrades? :)

**Comment by ZeljkaBlazek** [comment]
@rosstuck, yes I have a script :)

**Comment by rosstuck** [comment]
All merged, thanks for the PR! :)

**Comment by ZeljkaBlazek** [comment]
Thank you @rosstuck

**Pull request merged**
