### PR TITLE
Fix bernard example

### PR DESCRIPTION
**Pull request by sagikazarmark**
@rosstuck Just realized this while preparing my Tactician talk

Although I am not 100% happy with this solution, it's okay temporarily

### CODE REVIEW

**Comment by rosstuck** [comment]
Hey, you're working on a Tactician talk? Cool, let me know if there's going to be a video or slides online, would love to see it :)

With this one, I totally see it as a quick fix but I'm worried about putting it in the docs. If there's one thing I've learned over the last couple years, it's that folks tend to take this stuff very literally and if we put this in there, I promise you more than a few well-meaning folks will actually put this in their applications and it'll stay there. How about we change it to adding a few "queue-able" commands as an example, then mention you can automate this with DI tags, naming conventions, config handlers, etc, whatever makes sense for people's apps.

Would that be a fair compromise? :)

**Comment by sagikazarmark** [comment]
> Hey, you're working on a Tactician talk? Cool, let me know if there's going to be a video or slides online, would love to see it :)

Will do.

> Would that be a fair compromise? :)

Yeah, sounds OK. PR was a good idea though, at least I won't forget about it.

**Comment by rosstuck** [comment]
:+1: Cool, sounds good! It is a clever trick, kudos :)

**Comment by sagikazarmark** [comment]
Seems like class names don't work either. Bernard escapes the namespaces too. I wonder how I used this in production so far.

**Comment by rosstuck** [comment]
Gonna close this one for now. I'm waiting to see how the naming convention stuff works in the bundle and then whatever ends up working there successfully will go into Tactician2 :)

**Pull request closed without merging**
