### PR TITLE
Added community plugin page.

### PR DESCRIPTION
**Pull request by frankdejonge**

### CODE REVIEW

**Comment by rosstuck** [comment]
Thanks, great idea! This will be awesome for #87 and #67 as well.

Will close #86 and #82 once I can flesh out the page a bit more.

**Comment by pawelbaranski** [comment]
Not sure if that is related but I was curious to see what's on that page and the url http://tactician.thephpleague.com/plugin/community-plugins returns 404

**Comment by rosstuck** [comment]
Dang, I'm on the road right now and got another ping on Twitter just now.
This is probably a quick PR if someone wants to do it. Otherwise, will get
to it tonight.

**Comment by frankdejonge** [comment]
@rosstuck just pushed the fix.

**Comment by rosstuck** [comment]
Awesome, thanks! Gonna update this page with a few other plugins soon.

**Pull request merged**
