### PR TITLE
Test against php 7.4 stable

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You need to change the dist to bionic.

**Comment by snapshotpl** [comment]
@GrahamCampbell travis works https://travis-ci.org/thephpleague/tactician/jobs/621076710?utm_medium=notification&utm_source=github_status It's problem with scrutinizer

**Comment by GrahamCampbell** [comment]
Ah, they must have added 7.4 trusty now. They hadn't done that this time yesterday. ;P

**Comment by rosstuck** [comment]
Thanks to both of you! :)

**Pull request merged**
