### PR TITLE
Added gitattributes file

### PR DESCRIPTION
**Pull request by hannesvdvreken**

### CODE REVIEW

**Comment by boekkooi** [comment]
Why are you not exporting the `LICENSE`? and `tests`, `phpunit.xml.dist`?

**Comment by hannesvdvreken** [comment]
Why would you need test files when all that is autoloaded when installed via composer is the src folder? License, I don't know, isn't it enough that it's defined in the composer.json file?

**Comment by rosstuck** [comment]
Wow, I never got an email for the original PR so I totally missed this. Many apologies @hannesvdvreken!

The exports here are in-line with the league recommendations so I'm inclined to accept them as is. Thanks!

**Comment by hannesvdvreken** [comment]
:+1: no problem, you're welcome!

**Pull request merged**
