### PR TITLE
Test against php 8

### PR DESCRIPTION
**Pull request by snapshotpl**

### CODE REVIEW

**Comment by rosstuck** [comment]
I'd love to have this working because I want to add PHP8 annotation mapping in core, but I ran into the same version conflict issue as this PR and haven't had a chance to look into it yet. Any ideas?

**Comment by snapshotpl** [comment]
Looks like phpunit doesn't support php 8 yet https://phpunit.de/supported-versions.html

**Comment by flavioheleno** [comment]
This could probably be revised as deps have been updated to work with PHP 8:

```bash
$ php -v
PHP 8.0.0-dev (cli) (built: Oct  2 2020 18:00:09) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.0-dev, Copyright (c) Zend Technologies

$ composer -V
Composer version 1.10.15 2020-10-13 15:59:09

$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 44 installs, 0 updates, 0 removals
  - Installing squizlabs/php_codesniffer (3.5.6): Loading from cache
  - Installing dealerdirect/phpcodesniffer-composer-installer (v0.7.0): Downloading (100%)         
  - Installing phpstan/phpstan (0.12.50): Downloading (100%)         
  - Installing phpstan/extension-installer (1.0.5): Downloading (100%)         
  - Installing psr/container (1.0.0): Loading from cache
  - Installing phpstan/phpdoc-parser (0.4.9): Loading from cache
  - Installing slevomat/coding-standard (6.4.1): Downloading (100%)         
  - Installing doctrine/coding-standard (8.1.0): Downloading (100%)         
  - Installing roave/security-advisories (dev-latest ba5d234)
  - Installing nikic/php-parser (v4.10.2): Loading from cache
  - Installing sebastian/version (3.0.2): Loading from cache
  - Installing sebastian/type (2.3.0): Loading from cache
  - Installing sebastian/resource-operations (3.0.3): Loading from cache
  - Installing sebastian/recursion-context (4.0.3): Loading from cache
  - Installing sebastian/object-reflector (2.0.3): Loading from cache
  - Installing sebastian/object-enumerator (4.0.3): Loading from cache
  - Installing sebastian/global-state (5.0.1): Loading from cache
  - Installing sebastian/exporter (4.0.3): Loading from cache
  - Installing sebastian/environment (5.1.3): Loading from cache
  - Installing sebastian/diff (4.0.3): Loading from cache
  - Installing sebastian/comparator (4.0.5): Loading from cache
  - Installing sebastian/code-unit (1.0.7): Loading from cache
  - Installing sebastian/cli-parser (1.0.1): Loading from cache
  - Installing phpunit/php-timer (5.0.2): Loading from cache
  - Installing phpunit/php-text-template (2.0.3): Loading from cache
  - Installing phpunit/php-invoker (3.1.1): Loading from cache
  - Installing phpunit/php-file-iterator (3.0.5): Loading from cache
  - Installing theseer/tokenizer (1.2.0): Loading from cache
  - Installing sebastian/lines-of-code (1.0.1): Loading from cache
  - Installing sebastian/complexity (2.0.1): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (2.0.3): Loading from cache
  - Installing phpunit/php-code-coverage (9.2.0): Loading from cache
  - Installing doctrine/instantiator (1.3.1): Loading from cache
  - Installing phpdocumentor/reflection-common (2.2.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.18.1): Loading from cache
  - Installing webmozart/assert (1.9.1): Loading from cache
  - Installing phpdocumentor/type-resolver (1.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (5.2.2): Loading from cache
  - Installing phpspec/prophecy (1.12.1): Loading from cache
  - Installing phar-io/version (3.0.2): Loading from cache
  - Installing phar-io/manifest (2.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.10.1): Loading from cache
  - Installing phpunit/phpunit (9.4.1): Loading from cache
  - Installing phpstan/phpstan-phpunit (0.12.16): Loading from cache
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (*)
phpunit/phpunit suggests installing ext-soap (*)
phpunit/phpunit suggests installing ext-xdebug (*)
Writing lock file
Generating autoload files
29 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../doctrine/coding-standard/lib,../../slevomat/coding-standard
phpstan/extension-installer: Extensions installed
> phpstan/phpstan-phpunit: installed

$ ./vendor/bin/phpunit 
PHPUnit 9.4.1 by Sebastian Bergmann and contributors.

Warning:       Your XML configuration validates against a deprecated schema.
Suggestion:    Migrate your XML configuration using "--migrate-configuration"!

.......................                                           23 / 23 (100%)

Time: 00:00.052, Memory: 6.00 MB

OK (23 tests, 37 assertions)
```

**Comment by rosstuck** [comment]
Closed in favor of #145, thanks for your effort on this @snapshotpl, I appreciate it!

**Pull request closed without merging**
