### PR TITLE
Config improvements

### PR DESCRIPTION
**Pull request by sagikazarmark**
* Added [Editorconfig](http://editorconfig.org/)
* Updated LICENSE year
* Filter specific inclusions instead of exclusions in scrutinizer config
* Adds `travis_retry` to travis config (see [this](http://blog.travis-ci.com/2013-05-20-network-timeouts-build-retries/) for reference)

### CODE REVIEW

**Comment by rosstuck** [comment]
Thanks a ton, nice catch on the License file!

Any objection to setting YAML to 4 spaces so it's consistent? I know Ruby tends to use 2 spaces but a lot of the PHP world uses 4. I'm willing to go through and make it consistent.

**Comment by sagikazarmark** [comment]
Since YAML is not PHP, I think it's better to keep it two spaces. I think that became kind of a standard now. But I don't insist on it, that doesn't really matter.

**Comment by rosstuck** [comment]
Just polled two chat rooms, one was unanimously 4 spaces, the other was all votes for...tabs.

So, I propose 4 spaces here and ultimate vengeance up on the tab people.

**Comment by sagikazarmark** [comment]
Tabs? Those are invalid votes :D ...tabs are invalid in YAML, so they didn't even know what they were saying. :D

**Comment by sagikazarmark** [comment]
Done, but still against it.

**Comment by rosstuck** [comment]
Duly noted and thank you for doing it regardless :)

**Pull request merged**
